# Generated by Django 3.1.4 on 2021-01-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
