# Generated by Django 3.1.4 on 2021-01-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(verbose_name='lesson date'),
        ),
    ]
