# Generated by Django 3.1.4 on 2021-01-05 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210105_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
