# Generated by Django 3.1.4 on 2021-01-05 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20210105_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson',
            new_name='instrument',
        ),
    ]
